spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ec-db
    username: postgres
    password: choosePSW!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

