version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=choosePSW!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ec-db
  keycloak-server:
    image: bitnami/keycloak:22.0.5
    hostname: keycloak-server
    ports:
      - "8081:8081"
    environment:
      - "KEYCLOAK_ADMIN_USER=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KEYCLOAK_DATABASE_PORT=5432"
      - "KEYCLOAK_DATABASE_NAME=keycloak"
      - "KEYCLOAK_DATABASE_USER=postgres"
      - "KEYCLOAK_DATABASE_PASSWORD=choosePSW!"
      - "KEYCLOAK_DATABASE_SCHEMA=public"
    depends_on:
      - postgres
volumes:
  db:
    driver: local