version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=choosePSW!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ec-db
volumes:
  db:
    driver: local